schema = 3

[mod]
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.6.0"
    hash = "sha256-E8/cwio4xR8buCryR4HwR7+agb4M3zqgXSm7rBglmIY="
  [mod."connectrpc.com/connect"]
    version = "v1.18.1"
    hash = "sha256-ACtfiSMLBkGwUQ/Y6MVduWcKNOZzeI4aBSLzAoyfM6I="
  [mod."dario.cat/mergo"]
    version = "v1.0.1"
    hash = "sha256-wcG6+x0k6KzOSlaPA+1RFxa06/RIAePJTAjjuhLbImw="
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/ClickHouse/ch-go"]
    version = "v0.65.1"
    hash = "sha256-fmJMrpY0q2Z/OA/sCJYFjCtzAAQ3l1KQBwy4toLv12U="
  [mod."github.com/ClickHouse/clickhouse-go/v2"]
    version = "v2.33.0"
    hash = "sha256-7wQdNzej8Khj/EZPBs1gHrKTNrllukjuMYdDXZGAts4="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.2"
    hash = "sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU="
  [mod."github.com/ProtonMail/go-crypto"]
    version = "v1.1.5"
    hash = "sha256-N5Zn0f/NF3ezyGou2kRw9BwM25feJqnp7TPkRt6oK6I="
  [mod."github.com/andybalholm/brotli"]
    version = "v1.1.1"
    hash = "sha256-kCt+irK1gvz2lGQUeEolYa5+FbLsfWlJMCd5hm+RPgQ="
  [mod."github.com/avast/retry-go/v4"]
    version = "v4.6.0"
    hash = "sha256-K+CeNufj84bL5bMkxZkxGPfkkDQQtC6cfyofPCsn+iU="
  [mod."github.com/bradleyfalzon/ghinstallation/v2"]
    version = "v2.14.0"
    hash = "sha256-u296iVEWwGyyp1uziaBSSOoN59SpHJcxcnKnjMJUqQs="
  [mod."github.com/cloudflare/circl"]
    version = "v1.6.0"
    hash = "sha256-a+SVfnHYC8Fb+NQLboNg5P9sry+WutzuNetVHFVAAo0="
  [mod."github.com/cyphar/filepath-securejoin"]
    version = "v0.4.1"
    hash = "sha256-NOV6MfbkcQbfhNmfADQw2SJmZ6q1nw0wwg8Pm2tf2DM="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/emirpasic/gods"]
    version = "v1.18.1"
    hash = "sha256-hGDKddjLj+5dn2woHtXKUdd49/3xdsqnhx7VEdCu1m4="
  [mod."github.com/facebookgo/clock"]
    version = "v0.0.0-20150410010913-600d898af40a"
    hash = "sha256-Qh3po2B69wTmUwMS8QcJ3Lz3GpGlN5YPjcVQijXvcvw="
  [mod."github.com/fatih/structs"]
    version = "v1.1.0"
    hash = "sha256-OCmubTLF1anwNnkvFZDYHnF6hFlX0WDoe/9+dDlaMPM="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.8"
    hash = "sha256-ElqfQtnoGHyVqtN0mJjeWakQ6N5x+nVaX3+uOV7Q5Xk="
  [mod."github.com/go-faster/city"]
    version = "v1.0.1"
    hash = "sha256-D+tg4IMhFgmEObkZBw4qv9OVuBnCkv+Q0BQkbNIWxgk="
  [mod."github.com/go-faster/errors"]
    version = "v0.7.1"
    hash = "sha256-X+Yp7AiTfEQ0kOoixqOud8nN3XvfGLLB/ijXZ+SXhvc="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.1-0.20230307220236-3a3c6141e376"
    hash = "sha256-f4k0gSYuo0/q3WOoTxl2eFaj7WZpdz29ih6CKc8Ude8="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.6.2"
    hash = "sha256-VgbxcLkHjiSyRIfKS7E9Sn8OynCrMGUDkwFz6K2TVL4="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.14.0"
    hash = "sha256-8FAbi/r//Dcwoirr/4wYJykNAUWVb7MG67GXNpk8qTU="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.4"
    hash = "sha256-RrLHCu9l6k0XVobdZQJ9Sx/VTQcWjrdLR5BEG7yXTEQ="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.0.5"
    hash = "sha256-xDbwQfxNiH0gdNMCuxa6qKqiAeOhsnWm8MYSM+KISew="
  [mod."github.com/go-playground/locales"]
    version = "v0.14.1"
    hash = "sha256-BMJGAexq96waZn60DJXZfByRHb8zA/JP/i6f/YrW9oQ="
  [mod."github.com/go-playground/universal-translator"]
    version = "v0.18.1"
    hash = "sha256-2/B2qP51zfiY+k8G0w0D03KXUc7XpWj6wKY7NjNP/9E="
  [mod."github.com/go-playground/validator/v10"]
    version = "v10.25.0"
    hash = "sha256-198CQ0f+WC7UNxCCPg6rpogez6c5ivpignJNhx+z0W4="
  [mod."github.com/go-test/deep"]
    version = "v1.0.8"
    hash = "sha256-AKOpW32qcq1BTVEPC6MshiFA3ROucnmlJMIfvwYXvNY="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.2.1"
    hash = "sha256-3BcbxiZQp3eglk+vaYnRIDGT4dQ9K8aLrTPODbToI/Q="
  [mod."github.com/gobeam/stringy"]
    version = "v0.0.7"
    hash = "sha256-/tp2CfoybnkiOpT7JnCoa7VXCds+MrbzTb8WcAF5tLY="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.1"
    hash = "sha256-vG9QiSqJ/vRRzzjCry201EGwTUI2rgJkylCiKGFKgDY="
  [mod."github.com/golang-migrate/migrate/v4"]
    version = "v4.18.2"
    hash = "sha256-MvvA9obYARAp073BJrB2hX9nsV5ncA033VRssRzI+i0="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20241129210726-2c02b8208cf8"
    hash = "sha256-AdLZ3dJLe/yduoNvZiXugZxNfmwJjNQyQGsIdzYzH74="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/google/go-github/v69"]
    version = "v69.0.0"
    hash = "sha256-zTJ+RGD/1/kGIvtwyiobc+58FqphgJIjhfkE6shr8AE="
  [mod."github.com/google/go-querystring"]
    version = "v1.1.0"
    hash = "sha256-itsKgKghuX26czU79cK6C2n+lc27jm5Dw1XbIRgwZJY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/gosimple/slug"]
    version = "v1.15.0"
    hash = "sha256-Ra1X1VUxvpqYcnGZe5AzXWxvbNQ2sntcfoTHGEC5eeU="
  [mod."github.com/gosimple/unidecode"]
    version = "v1.0.1"
    hash = "sha256-/Tf2+eYHUuf0YWHMIVHHhgswiRLaAJBp0IAScmxrrbc="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.4.0"
    hash = "sha256-0UymBjkg41C9MPqkBLz/ZY9WbimZrabpJk+8C/X63h8="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.22.0"
    hash = "sha256-XiTsDCKK27Wn77deJ6X2ulIjqahXgOxA7t2YCsLltFY="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.2"
    hash = "sha256-FEh0GwrkTlFPZiqT6m3jYg5OV62/LHs/otMQuJfcMNw="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/jeffwelling/git2go/v37"]
    version = "v37.0.4"
    hash = "sha256-dmz9yImS9f6IkoP725P9XqTCJ0T1/q5EcoZp/YRUBAI="
    replaced = "github.com/breuhq/git2go/v37"
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.2.0"
    hash = "sha256-Ta7ZOmyX8gG5tzWbY2oES70EJPfI90U7CIJS9EAce0s="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/knadh/koanf/maps"]
    version = "v0.1.1"
    hash = "sha256-tUjNmbUFArrbblgjAqqiqAd6jRS8lE6LY98x/9yTS6k="
  [mod."github.com/knadh/koanf/providers/env"]
    version = "v1.0.0"
    hash = "sha256-K72VnJH5wFtTFGJUC41irh4DMXe1lkGtr6UxFbwqvTY="
  [mod."github.com/knadh/koanf/providers/structs"]
    version = "v0.1.0"
    hash = "sha256-H7FWUf9Atc97hBLMAkW/u54d+7pnHWcWqyGYjqEQYl0="
  [mod."github.com/knadh/koanf/v2"]
    version = "v2.1.2"
    hash = "sha256-g6GneudT1prBdKSofPuQJFvVcc6nYBJrmwfcpLWsWxQ="
  [mod."github.com/labstack/echo/v4"]
    version = "v4.13.3"
    hash = "sha256-vvVnNfy9w5sX3e6v8pz2Xt9fnhX5NyLY9OuEGZwZnMQ="
  [mod."github.com/labstack/gommon"]
    version = "v0.4.2"
    hash = "sha256-395+BETDpv15L2lsCiEccwakXgEQxKHlYBAU0Ot3qhY="
  [mod."github.com/leodido/go-urn"]
    version = "v1.4.0"
    hash = "sha256-Q6kplWkY37Tzy6GOme3Wut40jFK4Izun+ij/BJvcEu0="
  [mod."github.com/lib/pq"]
    version = "v1.10.9"
    hash = "sha256-Gl6dLtL+yk6UrTTWfas43aM4lP/pNa2l7+ITXnjQyKs="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/nexus-rpc/sdk-go"]
    version = "v0.1.0"
    hash = "sha256-1oQ2WEzQTUxD0wes7lHRdgPEoRnqgbspjS0ujwWYQXw="
  [mod."github.com/paulmach/orb"]
    version = "v0.11.1"
    hash = "sha256-oh5J5jl15FZwNm0jiYvPxNprMbufuSOELtvYHk1LLNs="
  [mod."github.com/pborman/uuid"]
    version = "v1.2.1"
    hash = "sha256-mwbymphWEvqBdxgLk3kU43JOSoGD3P9eDPV9k4Z5Nlg="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.22"
    hash = "sha256-mxO2jXM6O2yzZjkJeck+C8ncLZs/5EGoMQU1yQh/row="
  [mod."github.com/pjbgf/sha1cd"]
    version = "v0.3.2"
    hash = "sha256-jdbiRhU8xc1C5c8m7BSCj71PUXHY3f7TWFfxDKKpUMk="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/robfig/cron"]
    version = "v1.2.0"
    hash = "sha256-au+MD6DEjpVRAjXWmmJbZRB5IdFfcIqGm6kBkkYNY1s="
  [mod."github.com/segmentio/asm"]
    version = "v1.2.0"
    hash = "sha256-zbNuKxNrUDUc6IlmRQNuJQzVe5Ol/mqp7srDg9IMMqs="
  [mod."github.com/sergi/go-diff"]
    version = "v1.3.2-0.20230802210424-5b0b94c5c0d3"
    hash = "sha256-UcLU83CPMbSoKI8RLvLJ7nvGaE2xRSL1RjoHCVkMzUM="
  [mod."github.com/sethvargo/go-password"]
    version = "v0.3.1"
    hash = "sha256-gGUQkrhnBbVxGgYnUDDTfI/rbPVZGI1EHu1/BlJac2o="
  [mod."github.com/shopspring/decimal"]
    version = "v1.4.0"
    hash = "sha256-U36bC271jQsjuWFF8BfLz4WicxPJUcPHRGxLvTz4Mdw="
  [mod."github.com/skeema/knownhosts"]
    version = "v1.3.1"
    hash = "sha256-kjqQDzuncQNTuOYegqVZExwuOt/Z73m2ST7NZFEKixI="
  [mod."github.com/slack-go/slack"]
    version = "v0.16.0"
    hash = "sha256-6TwIYHBSfXSTUxxoEKRnAK4vpg+u9GG6qqGZC5jFVf4="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.6"
    hash = "sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.2"
    hash = "sha256-gp+lNXE8zjO+qJDM/YbS6V43HFsYP6PKn4ux1qa5lZ0="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.3"
    hash = "sha256-l3pGB6IdzcPA/HLk93sSN6NM2pKPy+bVOoacR5RC2+c="
  [mod."go.breu.io/durex"]
    version = "v0.6.2"
    hash = "sha256-6YZcaLmpaRo+CtNh7pyZt3cS44La/wt9e/mkWBCmxTw="
  [mod."go.breu.io/graceful"]
    version = "v0.1.0"
    hash = "sha256-d7/JPGFXHlo0RCr/CbuhTZLU+7g3py9Rjy4DJRK9pAo="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.35.0"
    hash = "sha256-LHrBtBnyDtvJGtrXHMPIFe7U53B4bZzpePB4u8Xo4Bg="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.35.0"
    hash = "sha256-HC2+OGDe2rg0+E8WymQbUNoc249NXM1gIBJzK4UhcQE="
  [mod."go.step.sm/crypto"]
    version = "v0.59.1"
    hash = "sha256-XPw48iJVaucL+1aMO/frXuDUdzYQ+B6i3B9dpzXHgNc="
  [mod."go.temporal.io/api"]
    version = "v1.43.0"
    hash = "sha256-EoZV0C2NTxaLVuw7tHNr0BmHnv6T1kPgHJNYNYSHw7Y="
  [mod."go.temporal.io/sdk"]
    version = "v1.32.1"
    hash = "sha256-k/uszlvaG5Jj6dS8lLS3zp/nUoNvv+GtMV2nIZ1ZO2s="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."golang.org/x/crypto"]
    version = "v0.36.0"
    hash = "sha256-Np+suvZdMOXALDm4m8nDNa+QsvUV0rE0PEINuxCoKGM="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240719175910-8a7402abbf56"
    hash = "sha256-mHEPy0vbd/pFwq5ZAEKaehCeYVQLEFDGnXAoVgkCLPo="
  [mod."golang.org/x/net"]
    version = "v0.37.0"
    hash = "sha256-sZKbJISVdBwyuYRQgrraTKxeIORWlzK5hScceQ2dE58="
  [mod."golang.org/x/sync"]
    version = "v0.12.0"
    hash = "sha256-lPIbI6aXx+iKtFjPaXKNLEnuNfhHCVl7EQiE7alUvlM="
  [mod."golang.org/x/sys"]
    version = "v0.31.0"
    hash = "sha256-aulv5obCrhheMlSq7seUgP3C29nfZABwiQ4IBNisgME="
  [mod."golang.org/x/text"]
    version = "v0.23.0"
    hash = "sha256-TiYX1K4DYpP1dEV06whOm43xyOntjrPFi+VAdncoeCY="
  [mod."golang.org/x/time"]
    version = "v0.10.0"
    hash = "sha256-vnlAME3gDR6R4cbCmSYAlR1Rjc0yUpkufTOPNvCdf6Q="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250219182151-9fdb1cabc7b2"
    hash = "sha256-KHVPNDTNA4NJeqHAKwo7NpoHtOYebNgP9Fwsmcj4nDE="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250303144028-a0af3efb3deb"
    hash = "sha256-l/2ByVhr10DBqSp5y1d8mtEY3++RUZKg89FCEptT0nQ="
  [mod."google.golang.org/grpc"]
    version = "v1.71.0"
    hash = "sha256-hfFCLYYI/dCjKPkxNdG4rhbr3HDr1GPGv4QxbcoCK7o="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.5"
    hash = "sha256-isupBiQUrKPEFzK94k5cgzM3Ab5fMXp352/zcsXV1JU="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
